
# storage claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-storage
spec:
  hostPath: 
    path: /mnt/dir/
    type: DirectoryOrCreate